volumes:
  cloudflared-home:

services:
  cloudflared:
    image: ghcr.io/soab1/cloudflared-auto-dns:2025.9.1
    volumes:
      - cloudflared-home:/root
      - ./cloudflared-tunnel-config.yml:/etc/cloudflared/tunnel-config.yml
      - ./cert.pem:/root/.cloudflared/cert.pem
    network_mode: "host"
    restart: always
    environment:
      TUNNEL_NAME: TEST
