name: Build a Publish arm64 image
on:
  workflow_dispatch:

jobs:
  build:
    name: Push Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v4
        with:
          images: ghcr.io/${{ github.repository }}

      - name: set image env
        run: |
          echo "OWNER_LC=${OWNER,,}" >>${GITHUB_ENV}
          echo "DOCKER_IMAGE=$(echo ${{ github.repository }} | awk -F '/' '{print $2}')" >>${GITHUB_ENV}
          echo "IMAGE_TAG=$(grep -P -o "(?<=^FROM cloudflare/cloudflared\:)([0-9]+\.[0-9]+\.[0-9]+)" build-arm64/Dockerfile)" >>${GITHUB_ENV}
        env:
          OWNER: "${{ github.repository_owner }}"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Push to GitHub Packages
        uses: docker/build-push-action@v3
        with:
          context: |
            ./build-amd64
            ./build-arm64
          platforms: linux/amd64,linux/arm64/v8
          push: true
          tags: ghcr.io/${{ env.OWNER_LC }}/${{ env.DOCKER_IMAGE }}:${{ env.IMAGE_TAG }}