name: CI
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup env
        run: |
          env_json=$(echo "${SECRETS}" | jq -r 'to_entries | .[] | @json')
          for i in ${env_json}; do
          env_key=$(echo "$i" | jq -r '.key')
          env_value=$(echo "$i" | jq -r '.value')
          echo "TF_ENV_${env_key,,}=${env_value}" >>"$GITHUB_ENV"
          done
        env:
          SECRETS: ${{ toJson(secrets) }}
      
      - name: Run a one-line script
        run: |
          env | grep 'TF_ENV'