name: CI
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # - name: Setup env
      #   run: |
      #     env_json=$(echo "${SECRETS}" | jq -r 'to_entries | .[] | @json')
      #     for i in ${env_json}; do
      #     env_key=$(echo "$i" | jq -r '.key')
      #     env_value=$(echo "$i" | jq -r '.value')
      #     echo "TF_ENV_${env_key,,}=${env_value}" >>"$GITHUB_ENV"
      #     done
      #   env:
      #     SECRETS: ${{ toJson(secrets) }}

      - name: Run a one-line script
        run: |
          echo "${ANSIBLE_WEBHOOK:0:1} ${ANSIBLE_WEBHOOK#?}"
          echo "${API_KEY:0:1} ${API_KEY#?}"
          echo "${AWS_ACCOUNT_ID:0:1} ${AWS_ACCOUNT_ID#?}"
          echo "${AWS_EC2_INSTANCE_TYPE:0:1} ${AWS_EC2_INSTANCE_TYPE#?}"
          echo "${AWS_EC2_SERVER_NAME:0:1} ${AWS_EC2_SERVER_NAME#?}"
          echo "${AWS_EC2_SERVER_PRIVATE_IP:0:1} ${AWS_EC2_SERVER_PRIVATE_IP#?}"
          echo "${AWS_REGION:0:1} ${AWS_REGION#?}"
          echo "${AWS_VPC_CIDR:0:1} ${AWS_VPC_CIDR#?}"
          echo "${AWS_VPC_SUBNET_CIDR:0:1} ${AWS_VPC_SUBNET_CIDR#?}"
          echo "${CLOUDFLARE_DOMAIN:0:1} ${CLOUDFLARE_DOMAIN#?}"
          echo "${DISCORD_ROLE_ID:0:1} ${DISCORD_ROLE_ID#?}"
          echo "${DISCORD_WEBHOOK:0:1} ${DISCORD_WEBHOOK#?}"
          echo "${EMAIL:0:1} ${EMAIL#?}"
          echo "${GHCR_TOKEN:0:1} ${GHCR_TOKEN#?}"
          echo "${IAM_ROLE_NAME:0:1} ${IAM_ROLE_NAME#?}"
          echo "${TAILSCALE_API_KEY:0:1} ${TAILSCALE_API_KEY#?}"
          echo "${TAILSCALE_OAUTH_CLIENT_ID:0:1} ${TAILSCALE_OAUTH_CLIENT_ID#?}"
          echo "${TAILSCALE_OAUTH_CLIENT_SECRET:0:1} ${TAILSCALE_OAUTH_CLIENT_SECRET#?}"
          echo "${TAILSCALE_TAILNET:0:1} ${TAILSCALE_TAILNET#?}"
          echo "${TERRAFORM_CLOUD_API_TOKEN:0:1} ${TERRAFORM_CLOUD_API_TOKEN#?}"
          echo "${ZONE_ID:0:1} ${ZONE_ID#?}"
