name: CI
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # - name: Setup env
      #   run: |
      #     env_json=$(echo "${SECRETS}" | jq -r 'to_entries | .[] | @json')
      #     for i in ${env_json}; do
      #     env_key=$(echo "$i" | jq -r '.key')
      #     env_value=$(echo "$i" | jq -r '.value')
      #     echo "TF_VAR_${env_key,,}=${env_value}" >>"$GITHUB_ENV"
      #     done
      #   env:
      #     SECRETS: ${{ toJson(secrets) }}

      - name: Run a one-line script
        run: |
          echo "${TF_VAR_ansible_webhook:0:1} ${TF_VAR_ansible_webhook#?}"
          echo "${TF_VAR_api_key:0:1} ${TF_VAR_api_key#?}"
          echo "${TF_VAR_aws_account_id:0:1} ${TF_VAR_aws_account_id#?}"
          echo "${TF_VAR_aws_ec2_instance_type:0:1} ${TF_VAR_aws_ec2_instance_type#?}"
          echo "${TF_VAR_aws_ec2_server_name:0:1} ${TF_VAR_aws_ec2_server_name#?}"
          echo "${TF_VAR_aws_ec2_server_private_ip:0:1} ${TF_VAR_aws_ec2_server_private_ip#?}"
          echo "${TF_VAR_aws_region:0:1} ${TF_VAR_aws_region#?}"
          echo "${TF_VAR_aws_vpc_cidr:0:1} ${TF_VAR_aws_vpc_cidr#?}"
          echo "${TF_VAR_aws_vpc_subnet_cidr:0:1} ${TF_VAR_aws_vpc_subnet_cidr#?}"
          echo "${TF_VAR_cloudflare_domain:0:1} ${TF_VAR_cloudflare_domain#?}"
          echo "${TF_VAR_discord_role_id:0:1} ${TF_VAR_discord_role_id#?}"
          echo "${TF_VAR_discord_webhook:0:1} ${TF_VAR_discord_webhook#?}"
          echo "${TF_VAR_email:0:1} ${TF_VAR_email#?}"
          echo "${TF_VAR_ghcr_token:0:1} ${TF_VAR_ghcr_token#?}"
          echo "${TF_VAR_iam_role_name:0:1} ${TF_VAR_iam_role_name#?}"
          echo "${TF_VAR_tailscale_api_key:0:1} ${TF_VAR_tailscale_api_key#?}"
          echo "${TF_VAR_tailscale_oauth_client_id:0:1} ${TF_VAR_tailscale_oauth_client_id#?}"
          echo "${TF_VAR_tailscale_oauth_client_secret:0:1} ${TF_VAR_tailscale_oauth_client_secret#?}"
          echo "${TF_VAR_tailscale_tailnet:0:1} ${TF_VAR_tailscale_tailnet#?}"
          echo "${TF_VAR_terraform_cloud_api_token:0:1} ${TF_VAR_terraform_cloud_api_token#?}"
          echo "${TF_VAR_zone_id:0:1} ${TF_VAR_zone_id#?}"
