name: CI
run-name: ${{ github.workflow }} (${{ github.ref_name }})
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        name: test-summary
        with:
          script: |
            parametersTable = [
              [{ data: 'key', header: true}, { data: 'value', header: true }],
              ['branch', '${{ github.ref_name }}']
            ]
            retryCommamd = `gh workflow run --ref ${{ github.ref_name }} '${{ github.workflow }}'`

            await core.summary
              .addRaw("### TEST SUMMARY\n")
              .addTable(parametersTable)
              .addRaw("### RETRY COMMAND\n")
              .addCodeBlocke(retryCommand)
              .write()

      - uses: actions/checkout@v3

      - name: Setup env
        run: |
          env_json=$(echo "${SECRETS}" | jq -r 'to_entries | .[] | @json')
          for i in ${env_json}; do
          env_key=$(echo "$i" | jq -r '.key')
          env_value=$(echo "$i" | jq -r '.value')
          echo "TF_ENV_${env_key,,}=${env_value}" >>"$GITHUB_ENV"
          done
        env:
          SECRETS: ${{ toJson(secrets) }}
      
      - name: Run a one-line script
        run: |
          env | grep 'TF_ENV'